### ISSUE TITLE
scaling issue

### ISSUE THREAD

**Issue by kurtaa1** [enziop/mixamo_converter#6]
Hi, I found a problem with this add-on. I am using the add-on to create a root bone to the skeletal mesh rig abd the animations. However in Unreal Engine 4.16 the character is scaled up to a giant when I enable root motion. Is there any specific export settings I have to use?
/Dave

**Comment by enziop** [comment]
Hi Dave,
Can you give me some further information? I had the same problem too once, but i don't remember in which case it happened.
Did you download the animation with or without skin?
Did you import the animation and the skeleton to unreal from the same file, or did you import the animation to a previously imported skeleton. If yes: did you also 'mixamoconvert' the skeleton?

I already had a solution for it. The problem was, that the blender fbx exporter doesn't apply scale to Skeletons animations when exporting for different unit scale. So one has to scale the skeleton by 100, then apply scale and scale it down 0.01 again. If i had a testcase or testfile again i could implement it in the converter.

**Comment by enziop** [comment]
Hi Dave,
I found the problem case again
One more problem ist, that apply scale doesn'z work for keyframes in blender, i will include the functionality in the MixamoConverter in the next few days.
Stay Tuned
Enzio

**Comment by enziop** [comment]
Hi Dave,
I Implemented a Scaling factor now, just download the most recent version of master.
Let me know if it works for you and please report any problems you encounter.
Enzio

**Comment by kurtaa1** [comment]
Sorry for the late response. I tried installing the new version but I get an error message when I press the "convert single" button. It says "TypeError: HipToRoot() got an unexpected keyword argument 'use x'".

**Comment by enziop** [comment]
Hi,
i can not reproduce the error on my Side, did you properly reinstall the new version of the addon? It sounds like only one of two python files was updated properly on your side

**Comment by kurtaa1** [comment]
I must have reinstalled improperly. It works now. Thank you for the fix!

**Comment by enziop** [comment]
Hi, there is a fix upcoming which should solve the scaling problem (and also rotation) way better than this manual scaling workaround, it will apply transforms so the rig and the mesh will have scale 1 after conversion, it should get rid of any scaling issues
it should be in master sometime tomorrow

**Comment by enziop** [comment]
Hi, sorry for the months of delay. I just released a new version which fixes rotation and scaling issues and has some experimental features to fix some other problems. If you need compatibility with previously converted animations you should disable apply rotation option, but i don't recommend disabling it, because it has double inverse rotation of 90 degree cancelling each other out which can lead to problems in unreal where your character might flip back 90 degree in some cases.
if you stell have problems using it, let me know
