### ISSUE TITLE
Root bone not in a right position!

### ISSUE THREAD

**Issue by xtremertx** [enziop/mixamo_converter#65]
Hi, I have tried your plugin and...
Root bone is not in a right position in UE4, the green line represents a GRID and that should be up.

![image](https://user-images.githubusercontent.com/14142029/76485900-1574e400-641e-11ea-9264-67e190480008.png)

![image](https://user-images.githubusercontent.com/14142029/76486050-80261f80-641e-11ea-9ecb-95278b3bd2a2.png)

I have tried several settings and everything seems same. 
(using: Dwarf_Idle animation from mixamo)

**Comment by xtremertx** [comment]
And here the mixamo animation.

![image](https://user-images.githubusercontent.com/14142029/76486249-12c6be80-641f-11ea-91c5-1c951cb7b2d4.png)

Please give me some feedback...

**Comment by enziop** [comment]
Did you import an unconverted animation or model directly from mixamo and then imported the animation for that skeleton? That might be the fault. The asset that you use to import your Character (can be just a T-Pose animation) also has to be converted.

**Comment by xtremertx** [comment]
Yes I have used CONVERTED ANIMATIONS! And my asset is in a T-Pose and was converted, will try that again today...

**Comment by enziop** [comment]
I assume the problem was the initial import of your character, where the restpose is centered at the pelvis, and then importing converted animations from MixamoConverter. I will therefore close the Issue.
Having a default Mannequin with T-pose is not the point of this addon. It does not do retargeting, but just bone hierachy changes and hip and root bone rebaking.
If your initial character and the animations you have for that character use an A pose or a T pose as reference does not make any difference at all to this tool.
