### ISSUE TITLE
How does it even work?

### ISSUE THREAD

**Issue by Tigan3** [enziop/mixamo_converter#9]
I tried it and I tried doing it in many different ways. Please make more detailed instructions or a video (preferably start from download settings on the Mixamo website and end with a working root motion animation from Mixamo). I understood how to do the blender part but when I get to Unreal Engine I have no idea how to proceed. Thanks in advance. <3

**Comment by enziop** [comment]
The addon is still under heavy development and will change a lot in the next weeks as we currently use it in production and implement new features every few days. I will not yet make any tutorial video for the complete way from mixamo to unreal but i might in around 1 month when it is more feature complete and got rid of some problems which are currently still present.
But I can give you some keywords on it:
##Mixamo
- works best with characters which were rigged with mixamos autorigger
- download animations as FBX with skin and no keyframe reduction
##Blender
- batchconvert your animations as described in the readme
##Unreal
- first import: import one of the converted animations to unreal with mesh and skeletal mesh
- rename your skeleton and mesh in unreal to not have the name of the animation but of your character
- import any further animations and untick import mesh and select the skeleton which the animation will then be applied to
- open the animation in unreal. on the left side in asset details there is a pane named Root Motion. Tick EnableRootMotion
- in order to preview it in the 3d viewport of the animation settings: at the top of the 3D viewport click Show->Process Root Motion

Now you should be able to see the root motion working

**Comment by enziop** [comment]
I recommend to wait until tomorrow evening and then get the recent version because i just implemented some major fixes for rotation and scaling issues

**Comment by Tigan3** [comment]
Thanks! It is great that you are working hard on this (and especially that you are giving it for free). I am looking forward to seeing the final product. Good luck!

**Comment by Tigan3** [comment]
What happened :(

**Comment by enziop** [comment]
I'm sorry, I was very busy last week, I'm trying to release it, till friday this week.

**Comment by enziop** [comment]
So now finally version 1.0.3 has beed released to master, it resolves some issues with wrong rotation and scaling of the character and has experimental workarounds for some errors.
for most cases its best to just use the standard configuration
sorry for the delay
Enzio
